### ISSUE TITLE
Autocomplete freezes the interface

### ISSUE THREAD

**Issue by tobia** [b123400/purescript-ide-sublime#6]
Whenever the autocomplete code is run, especially after typing a single letter, the editor interface is completely frozen for several seconds. Nothing responds, not even the menus.

Autocomplete should be run in a background thread, so that the user can keep on using the editor while the plugin is waiting to get results from purs.

**Comment by b123400** [comment]
Yeah I am aware of this issue as well. The problem is [Sublime Text's API](https://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.ViewEventListener) (The `on_query_completions` function) requires results to be returned immediately, and it's called on the main thread.

While it's not a solution, there is an option in the preference `auto_complete_timeout`, which allows you to set a time limit on auto complete query.
